- name: déploiement de demoapp sur cluster k8s
  hosts: k8s-master
  become: false
  gather_facts: false
  tasks:
  - name: Vérifier cluster k8s
    command: kubectl cluster-info
    register: k8sClusterOk
  - name: deploy demoapp
    command: kubectl apply -f /tmp/demoapp-manifest.yml

